### ISSUE TITLE
possible mistake in u vector for adm1_DAE2_bsm2.c in ADM1 DAE2

### ISSUE THREAD

**Issue by CaptainFerMag** [wwtmodels/Anaerobic-Digestion-Models#5]
line 113:

`y[7] = u[93]; /* Sh2 */`

is u[93] Sh2 or SH+ ? and then u[100] is the actual Sh2?

and line 128:

`y[28] = u[94];         /* SH+*/`

is u[94] SH+ or Sva- ?

**Comment by wwtmodels** [comment]
I think @xfalsina should be capable of answering this :) 

/ Sebastian

**Comment by wwtmodels** [comment]
Hi,

Line 113

y[7] = u[93];   /* Sh2 */

This is the result of the algebraic solver (sh2solv_adm1.c) for H2 (effluent value) 

Line 123

 y[26] = u[7];             /* H2 */

This is the influent H2 

Line 125

  y[27] = -log10(u[94]);    /* pH */

This is the result of the speciation model (Phsolv_bsm2.c)
where x [0] is H+ (first output)

**Comment by CaptainFerMag** [comment]
hi, 
thank you very much for your response.
can you please add a file or documentation to explain the order of states in signals (initial, input, output)? is it already mentioned somewhere? I tried to map the signals to states myself and that is how I came up with the issue. I will check my mapping with your answer.
